import { ConfiguratorCategory, ConfiguratorProduct } from "./configuratorTypes";

export const systemUnitCategories: ConfiguratorCategory[] = [
  {
    key: "processor",
    title: "პროცესორი",
    icon: "/images/processor.svg",
  },
  {
    key: "motherboard",
    title: "დედა დაფა",
    icon: "/images/motherboard.svg",
  },
  {
    key: "ram",
    title: "ოპერატიული მეხსიერება",
    icon: "/images/ram.svg",
  },
  {
    key: "gpu",
    title: "ვიდეობარათი",
    icon: "/images/gpu.svg",
  },
  {
    key: "psu",
    title: "კვების ბლოკი",
    icon: "/images/psu.svg",
  },
  {
    key: "cooler",
    title: "პროცესორის გამაგრილებელი",
    icon: "/images/cooler.svg",
  },
  {
    key: "case",
    title: "ქეისი",
    icon: "/images/case.svg",
  },
  {
    key: "drive",
    title: "მყარი დისკი",
    icon: "/images/Harddrive.svg",
  },
  {
    key: "storage",
    title: "SSD მეხსიერება",
    icon: "/images/ssd.svg",
  },
  {
    key: "caseFan",
    title: "ქეისის ქულერი",
    icon: "/images/fan.svg",
  },
  {
    key: "os",
    title: "სისტემის ლიცენზია",
    icon: "/images/windows.svg",
  },
];

export const peripheralCategories: ConfiguratorCategory[] = [
  {
    key: "monitor",
    title: "მონიტორი",
    icon: "/images/monitor.svg",
  },
  {
    key: "headphones",
    title: "ყურსასმენი",
    icon: "/images/headphones.svg",
  },
  {
    key: "keyboard",
    title: "კლავიატურა",
    icon: "/images/keyboard.svg",
  },
  {
    key: "mouse",
    title: "მაუსი",
    icon: "/images/mouse.svg",
  },
  {
    key: "microphone",
    title: "მიკროფონი",
    icon: "/images/microphone.svg",
  },
  {
    key: "speaker",
    title: "დინამიკი",
    icon: "/images/speaker.svg",
  },
];

export const configuratorProducts: ConfiguratorProduct[] = [
  {
    id: 1,
    category: "motherboard",
    title: "MSI B650 Gaming Plus WiFi",
    image: "/images/motherboard.svg",
    price: 450,
    stock: 12,
    specs: [
      { label: "ჩიპსეტი", value: "B650" },
      { label: "სოკეტი", value: "AM5" },
      { label: "მეხსიერება", value: "DDR5" },
      { label: "ფორმფაქტორი", value: "ATX" },
      { label: "PCI Express", value: "PCIe 4.0" },
    ],
  },
  {
    id: 11,
    category: "motherboard",
    title: "MSI PRO B650M-P",
    image: "/images/motherboard.svg",
    price: 390,
    stock: 6,
    specs: [
      { label: "ჩიპსეტი", value: "B650" },
      { label: "სოკეტი", value: "AM5" },
      { label: "მეხსიერება", value: "DDR5" },
      { label: "ფორმფაქტორი", value: "Micro-ATX" },
      { label: "PCI Express", value: "PCIe 4.0" },
    ],
  },
  {
    id: 12,
    category: "motherboard",
    title: "Asus TUF Gaming B650-Plus WiFi",
    image: "/images/motherboard.svg",
    price: 520,
    stock: 6,
    specs: [
      { label: "ჩიპსეტი", value: "B650" },
      { label: "სოკეტი", value: "AM5" },
      { label: "მეხსიერება", value: "DDR5" },
      { label: "ფორმფაქტორი", value: "ATX" },
      { label: "Wi-Fi", value: "დიახ" },
    ],
  },
  {
    id: 13,
    category: "motherboard",
    title: "Asus Prime B550M-A",
    image: "/images/motherboard.svg",
    price: 280,
    stock: 6,
    specs: [
      { label: "ჩიპსეტი", value: "B550" },
      { label: "სოკეტი", value: "AM4" },
      { label: "მეხსიერება", value: "DDR4" },
      { label: "ფორმფაქტორი", value: "Micro-ATX" },
    ],
  },
  {
    id: 14,
    category: "motherboard",
    title: "Gigabyte B650 Eagle AX",
    image: "/images/motherboard.svg",
    price: 470,
    stock: 0,
    specs: [
      { label: "ჩიპსეტი", value: "B650" },
      { label: "სოკეტი", value: "AM5" },
      { label: "მეხსიერება", value: "DDR5" },
      { label: "ფორმფაქტორი", value: "ATX" },
      { label: "Wi-Fi", value: "დიახ" },
    ],
  },
  {
    id: 15,
    category: "motherboard",
    title: "Gigabyte A520M K V2",
    image: "/images/motherboard.svg",
    price: 190,
    stock: 6,
    specs: [
      { label: "ჩიპსეტი", value: "A520" },
      { label: "სოკეტი", value: "AM4" },
      { label: "მეხსიერება", value: "DDR4" },
      { label: "ფორმფაქტორი", value: "Micro-ATX" },
    ],
  },
  {
    id: 16,
    category: "motherboard",
    title: "AsRock B650M Pro RS",
    image: "/images/motherboard.svg",
    price: 410,
    stock: 6,
    specs: [
      { label: "ჩიპსეტი", value: "B650" },
      { label: "სოკეტი", value: "AM5" },
      { label: "მეხსიერება", value: "DDR5" },
      { label: "ფორმფაქტორი", value: "Micro-ATX" },
    ],
  },
  {
    id: 17,
    category: "motherboard",
    title: "AsRock A620M-HDV/M.2",
    image: "/images/motherboard.svg",
    price: 260,
    stock: 6,
    specs: [
      { label: "ჩიპსეტი", value: "A620" },
      { label: "სოკეტი", value: "AM5" },
      { label: "მეხსიერება", value: "DDR5" },
      { label: "ფორმფაქტორი", value: "Micro-ATX" },
    ],
  },
  {
    id: 2,
    category: "processor",
    title: "AMD Ryzen 5 7600X",
    image: "/images/processor.svg",
    price: 620,
    stock: 6,
    specs: [
      { label: "ბირთვი", value: "6" },
      { label: "ნაკადი", value: "12" },
      { label: "სოკეტი", value: "AM5" },
    ],
  },
  {
    id: 3,
    category: "ram",
    title: "Kingston Fury Beast 32GB DDR5",
    image: "/images/ram.svg",
    price: 290,
    stock: 6,
    specs: [
      { label: "მოცულობა", value: "32GB" },
      { label: "ტიპი", value: "DDR5" },
      { label: "სიხშირე", value: "6000MHz" },
    ],
  },
  {
    id: 4,
    category: "gpu",
    title: "RTX 4060 8GB",
    image: "/images/gpu.svg",
    price: 1200,
    stock: 6,
    specs: [
      { label: "მეხსიერება", value: "8GB" },
      { label: "ტიპი", value: "GDDR6" },
    ],
  },
  {
    id: 5,
    category: "monitor",
    title: "LG UltraGear 27”",
    image: "/images/monitor.svg",
    price: 780,
    stock: 6,
    specs: [
      { label: "ზომა", value: "27''" },
      { label: "განახლება", value: "144Hz" },
      { label: "პანელი", value: "IPS" },
    ],
  },
  {
    id: 6,
    category: "headphones",
    title: "Logitech G435",
    image: "/images/headphones.svg",
    price: 220,
    stock: 6,
    specs: [
      { label: "ტიპი", value: "Wireless" },
      { label: "მიკროფონი", value: "დიახ" },
    ],
  },
  {
    id: 7,
    category: "keyboard",
    title: "Redragon Kumara",
    image: "/images/keyboard.svg",
    price: 130,
    stock: 6,
    specs: [
      { label: "ტიპი", value: "Mechanical" },
      { label: "განათება", value: "RGB" },
    ],
  },
  {
    id: 8,
    category: "mouse",
    title: "Logitech G102",
    image: "/images/mouse.svg",
    price: 75,
    stock: 6,
    specs: [{ label: "სენსორი", value: "8000 DPI" }],
  },
  {
    id: 9,
    category: "microphone",
    title: "HyperX SoloCast",
    image: "/images/microphone.svg",
    price: 180,
    stock: 6,
    specs: [{ label: "კავშირი", value: "USB" }],
  },
  {
    id: 10,
    category: "speaker",
    title: "Edifier R1280T",
    image: "/images/speaker.svg",
    price: 340,
    stock: 6,
    specs: [{ label: "სიმძლავრე", value: "42W" }],
  },
  {
    id: 18,
    category: "psu",
    title: "Corsair CV650 650W 80+ Bronze",
    image: "/images/psu.svg",
    price: 210,
    stock: 8,
    specs: [
      { label: "სიმძლავრე", value: "650W" },
      { label: "სერტიფიკატი", value: "80+ Bronze" },
      { label: "ფორმფაქტორი", value: "ATX" },
      { label: "მოდულარული", value: "არა" },
    ],
  },
  {
    id: 19,
    category: "cooler",
    title: "DeepCool AG400 CPU Cooler",
    image: "/images/cooler.svg",
    price: 95,
    stock: 10,
    specs: [
      { label: "ტიპი", value: "Air Cooler" },
      { label: "სოკეტი", value: "AM4 / AM5" },
      { label: "ვენტილატორი", value: "120mm" },
      { label: "RGB", value: "არა" },
    ],
  },
  {
    id: 20,
    category: "case",
    title: "DeepCool CC560 White Case",
    image: "/images/case.svg",
    price: 180,
    stock: 7,
    specs: [
      { label: "ფორმფაქტორი", value: "ATX" },
      { label: "ფერი", value: "White" },
      { label: "ქულერები", value: "4 Fan Included" },
      { label: "გვერდი", value: "Tempered Glass" },
    ],
  },
  {
    id: 21,
    category: "storage",
    title: "Kingston NV2 1TB NVMe SSD",
    image: "/images/ssd.svg",
    price: 160,
    stock: 14,
    specs: [
      { label: "მოცულობა", value: "1TB" },
      { label: "ტიპი", value: "NVMe SSD" },
      { label: "ინტერფეისი", value: "PCIe 4.0" },
      { label: "ფორმფაქტორი", value: "M.2 2280" },
    ],
  },
  {
    id: 22,
    category: "drive",
    title: "Seagate Barracuda 1TB HDD",
    image: "/images/Harddrive.svg",
    price: 120,
    stock: 9,
    specs: [
      { label: "მოცულობა", value: "1TB" },
      { label: "ტიპი", value: "HDD" },
      { label: "სიჩქარე", value: "7200 RPM" },
      { label: "ინტერფეისი", value: "SATA III" },
    ],
  },
  {
    id: 23,
    category: "caseFan",
    title: "DeepCool RF120 RGB Fan",
    image: "/images/fan.svg",
    price: 45,
    stock: 20,
    specs: [
      { label: "ზომა", value: "120mm" },
      { label: "განათება", value: "RGB" },
      { label: "კავშირი", value: "4-pin" },
    ],
  },
  {
    id: 24,
    category: "os",
    title: "Windows 11 Pro License",
    image: "/images/windows.svg",
    price: 90,
    stock: 30,
    specs: [
      { label: "ვერსია", value: "Windows 11 Pro" },
      { label: "ლიცენზია", value: "Digital Key" },
      { label: "არქიტექტურა", value: "64-bit" },
    ],
  },
];
